const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      brand: 'Nike',
      description: 'High quality nike shirt',
      condition: 'Brand New',
      pick_up_loc: 'Mumbai',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas_fit-shirt',
      category: 'Shirt',
      image: '/images/p2.jpg',
      price: 100,
      brand: 'Adidas',
      description: 'High quality nike shirt',
      condition: 'Brand New',
      pick_up_loc: 'Mumbai',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas_fit-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 150,
      brand: 'Adidas',
      description: 'High quality nike shirt',
      condition: 'Brand New',
      pick_up_loc: 'Mumbai',
    },
    {
      name: 'Nike Slim pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 80,
      brand: 'Nike',
      description: 'High quality nike shirt',
      condition: 'Brand New',
      pick_up_loc: 'Mumbai',
    },
  ],
};
export default data;
