const data = {
  products: [
    {
      name: 'BAJAJ mixer-grinder',
      slug: 'BAJAJ_mixer_grinder',
      category: 'appliance',
      image: '/images/p1.jpg',
      price: '120 - 140',
      brand: 'Bajaj',
      description: 'bajaj mixer',
      condition: 'Brand New',
      pick_up_loc: 'Mumbai',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas_fit-shirt',
      category: 'Shirt',
      image: '/images/p2.jpg',
      price: '50 - 100',
      brand: 'Adidas',
      description: 'High quality nike shirt',
      condition: 'Brand New',
      pick_up_loc: 'Mumbai',
    },
    {
      name: 'Mutant Ape NFT',
      slug: 'Mutant_Ape_NFT',
      category: 'NFT',
      image: '/images/p3.jpg',
      price: '70 - 120',
      brand: 'bored ape',
      description: 'Mutant ape yacht club nft artwork collection ',
      condition: 'NA',
      pick_up_loc: 'Digital',
    },
    {
      name: 'Nike Slim pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: '80 - 100',
      brand: 'Nike',
      description: 'High quality nike shirt',
      condition: 'Brand New',
      pick_up_loc: 'Mumbai',
    },
  ],
};
export default data;
